services:
  - type: web
    name: sabapplier-backend        
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application" 
                 