services:
  - type: web
    name: sabapplier-backend        
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn backend.wsgi:application"
                 